spring:
    datasource:
        username: root
        password: 123456789
        url: jdbc:mysql://localhost:3306/security_test
    jpa:
        show-sql: false
        open-in-view: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        database: mysql
jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-time: 7200000
    refresh-token:
        expiration-time: 86400000
server:
    port: 8082